oauth_server_sso.settings:
  type: mapping
  label: Settings
  mapping:
    oauth_server_sso_customer_admin_email:
      type: 'NULL'
    oauth_server_sso_license_key:
      type: 'NULL'
    oauth_server_sso_customer_id:
      type: string
    oauth_server_sso_customer_admin_token:
      type: string
    oauth_server_sso_customer_api_key:
      type: string
    oauth_server_sso_force_auth:
      type: boolean
    oauth_server_sso_enable_backdoor:
      type: boolean
    oauth_server_sso_default_relaystate:
      type: string
    oauth_server_sso_name:
      type: string
    oauth_server_sso_issuer:
      type: string
    oauth_server_sso_login_url:
      type: string
    oauth_server_sso_logout_url:
      type: string
    oauth_server_sso_x509_certificate:
      type: string
    oauth_server_sso_response_signed:
      type: boolean
    oauth_server_sso_assertion_signed:
      type: boolean
    oauth_server_sso_enable_login:
      type: boolean
    oauth_server_sso_username_attribute:
      type: string
    oauth_server_sso_email_attribute:
      type: string
    oauth_server_sso_attr1_name:
      type: string
    oauth_server_sso_attr5_name:
      type: string
    oauth_server_sso_attr5_name:
      type: string
    oauth_server_sso_attr2_name:
      type: string
    oauth_server_sso_attr2_name:
      type: string
    oauth_server_sso_attr3_name:
      type: string
    oauth_server_sso_attr3_name:
      type: string
    oauth_server_sso_attr4_name:
      type: string
    oauth_server_sso_attr4_name:
      type: string
    oauth_server_sso_disable_autocreate_users:
      type: boolean
    oauth_server_sso_default_role:
      type: string
    oauth_server_sso_role1_name:
      type: string
    oauth_server_sso_role1_name:
      type: string
    oauth_server_sso_role2_name:
      type: string
    oauth_server_sso_role2_name:
      type: string
    oauth_server_sso_role3_name:
      type: string
    oauth_server_sso_role3_name:
      type: string
    oauth_server_sso_role4_name:
      type: string
    oauth_server_sso_role4_name:
      type: string
    oauth_server_sso_status:
      type: string
    oauth_server_sso_customer_admin_phone:
      type: 'NULL'
    oauth_server_sso_tx_id:
      type: 'NULL'
    oauth_server_sso_customer_admin_password:
      type: string
    oauth_server_sso_auto_redirect_to_idp:
      type: boolean
    oauth_server_sso_sp_issuer:
      type: string
    oauth_server_sso_login_by:
      type: integer
    oauth_server_sso_attr1_name:
      type: string
    oauth_server_sso_entity_id:
      type: string
    oauth_server_sso_base_url : 
      type: string  
    oauth_server_sso_acs_url:
      type: string  
    oauth_server_sso_nameid_attr_map:
      type: string